abstract: Kemuri Interpreter.
author: Tokuhiro Matsuno  C<< <tokuhiro __at__ mobilefactory.jp> >>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Language-Kemuri
no_index: 
  directory: 
    - inc
    - t
requires: 
  Switch: 0
version: 0.02
